### ISSUE TITLE
Vue warn after upgrading from 0.1.10 to 0.1.13

### ISSUE THREAD

**Issue by roophieini** [Semantic-UI-Vue/Semantic-UI-Vue#157]
Hello

I've got this error
`vue.esm.js?efeb:1717 TypeError: this.$options.events[key].bind is not a function
    at VueComponent.beforeCreate (index.js?119a:121)
    at callHook (vue.esm.js?efeb:2895)
    at VueComponent.Vue._init (vue.esm.js?efeb:4556)
    at new VueComponent (vue.esm.js?efeb:4728)
    at createComponentInstanceForVnode (vue.esm.js?efeb:4242)
    at init (vue.esm.js?efeb:4059)
    at createComponent (vue.esm.js?efeb:5512)
    at createElm (vue.esm.js?efeb:5460)
    at createChildren (vue.esm.js?efeb:5586)
    at createElm (vue.esm.js?efeb:5488)`

In SuiButton, SuiDropdown and SuiDropdownitem component after upgrading version of Semantic-UI-Vue. After that warn, most of the components doesn't work properly.

**Comment by ArStah** [comment]
And why you're updating to such old version of Sui-Vue?

**Comment by rabello98** [comment]
I'm having a similar problem ... when I use some component of semantic ui vue, I get the following message on the console:

TypeError: this. $ Options.events [key] .bind is not a function
Battery Tracking:
beforeCreate @ webpack-internal: /// 16: 121: 25
callHook @ webpack-internal: /// 1: 2919: 9 ....

Thanks to anyone who can help.

**Comment by mariolamacchia** [comment]
@rabello98 it's hard to give you an answer without a code. Please try to reproduce the error [here](https://codesandbox.io/s/n08n0krolj) so we can give you support.

@roophieini Closing this as it concerns an old version of Semantic UI Vue. We'll reopen it if you still have problems after upgrading to the latest version (0.2.6)

**Comment by b3f3** [comment]
I've the same issue with semantic-ui-vue 0.8.1.
You can see it in action here : https://codesandbox.io/s/7m0q4w7zqq
This problème is similar in #161
